export const cardsJSON = [
  {
    id: 'chrono_walker',
    title: 'хроно йокер',
    type: 'source',
    magicSign: 'illusion',
    src: 'chrono_walker',
    text: '<p>Все кидают кость. Вы +1 к своему броску за каждый различный «ЗНАК» в своем заклятии. 3 повреждения получит выбросивший наименьший результат.</p>',
    initiative: 0,
  },
  {
    id: 'sphinx',
    title: 'сфинксшин',
    type: 'source',
    magicSign: 'illusion',
    src: 'sphinx',
    text: '<p>Выберите и украдите Сокровище, принадлежащее любому противнику.</p>',
    initiative: 0,
  },
  {
    id: 'chuk_geck',
    title: 'чук и гек',
    type: 'source',
    magicSign: 'illusion',
    src: 'chuk_geck',
    text: '<p>Снимите 4 верхние карты Основной Колоды. Добавьте любые из открытых карт «Качество» в ваше заклятие, остальные сбросьте.</p>',
    initiative: 0,
  },
  {
    id: 'twins',
    title: 'пэт и хекуба',
    type: 'source',
    magicSign: 'illusion',
    src: 'twins',
    text: '<p>Целью карты «Действие» становятся ВСЕ противники.</p>',
    initiative: 0,
  },
  {
    id: 'doctor_root',
    title: 'док корнедрев',
    type: 'source',
    magicSign: 'nature',
    src: 'doctor_root',
    text: '<p>Вы восстанавливаете 3 ед. Жизни. Все противники кидают кость. У кого выпадает 6-ка, тоже восстанавливают 3 ед. Жизни.</p>',
    initiative: 0,
  },
  {
    id: 'fallen_rose',
    title: 'падшая роза',
    type: 'source',
    magicSign: 'nature',
    src: 'fallen_rose',
    text: '<p>Восстановите 1 ед. Жизни за каждый различный «ЗНАК» в вашем заклятии.</p>',
    initiative: 0,
  },
  {
    id: 'snout',
    title: 'мордохват',
    type: 'source',
    magicSign: 'nature',
    src: 'snout',
    text: '<p>Добавляйте кость к каждой Проверке силы в этом раунде.</p>',
    initiative: 0,
  },
  {
    id: 'king_oberon',
    title: 'король оберон',
    type: 'source',
    magicSign: 'nature',
    src: 'king_oberon',
    text: '<p>Восстановите 2 ед. Жизни.</p>',
    initiative: 0,
  },
  {
    id: 'fat_hag',
    title: 'толстая карга',
    type: 'source',
    magicSign: 'nature',
    src: 'fat_hag',
    text: '<p>Нанесите противнику слева по 1 повреждению за каждую карту в вашем заклятии.</p>',
    initiative: 0,
  },
  {
    id: 'midnight_merlin',
    title: 'полночный мерлин',
    type: 'source',
    magicSign: 'dark',
    src: 'midnight_merlin',
    text: '<p>Нанесите сильнейшему противнику по 1-му ранению за каждого живого мага. Затем возьмите карту «Дохлый маг».</p>',
    initiative: 0,
  },
  {
    id: 'voodoo_ben',
    title: 'вуду бен',
    type: 'source',
    magicSign: 'dark',
    src: 'voodoo_ben',
    text: '<p>Каждый противник бросает кость и получает столько повреждений сколько выпадет. Сбросьте одно Сокровище если оно у вас есть.</p>',
    initiative: 0,
  },
  {
    id: 'fairy_death',
    title: 'фея смерти',
    type: 'source',
    magicSign: 'dark',
    src: 'fairy_death',
    text: '<p>Нанесите любому противнику 2 повреждения. Если он умирает, снова повторите действие карты.</p>',
    initiative: 0,
  },
  {
    id: 'old_devil',
    title: 'старый бес',
    type: 'source',
    magicSign: 'dark',
    src: 'old_devil',
    text: '<p>Бросьте кость. Если выпало 1-3 получите столько повреждений. Если выпало 4-6 излечите столько повреждений.</p>',
    initiative: 0,
  },
  {
    id: 'psychomind',
    title: 'гадкий психомозг',
    type: 'source',
    magicSign: 'mystery',
    src: 'psychomind',
    text: '<p>Откройте 2 верхние карты Основной Колоды, Добавьте в свое заклятие те, у которых «ЗНАК» совпадает с уже имеющимся в вашем заклятии. Остаток сбросьте.</p>',
    initiative: 0,
  },
  {
    id: 'huckster',
    title: 'сэр барыга',
    type: 'source',
    magicSign: 'mystery',
    src: 'huckster',
    text: '<p>Вы получаете Сокровище. Все противники бросают кость. У кого выпала 6-ка тоже получает Сокровище.</p>',
    initiative: 0,
  },
  {
    id: 'wind_beard',
    title: 'ветро-бород',
    type: 'source',
    magicSign: 'mystery',
    src: 'wind_beard',
    text: '<p>Эта карта копирует текст карты «Действие», вашего заклятия.</p>',
    initiative: 0,
  },
  {
    id: 'professor',
    title: 'профессор престо',
    type: 'source',
    magicSign: 'mystery',
    src: 'professor',
    text: '<p>Нанесите 3 повреждения случайному противнику. Если в вашем заклятии есть карта «Дикая магия», получите Сокровище.</p>',
    initiative: 0,
  },
  {
    id: 'zmey_gorynych',
    title: 'змей горыныч',
    type: 'source',
    magicSign: 'element',
    src: 'zmey_gorynych',
    text: '<p>Нанесите по 1 повреждению каждому противнику за каждый различный «ЗНАК» в вашем заклятии.</p>',
    initiative: 0,
  },
  {
    id: 'magog',
    title: 'гог магмы',
    type: 'source',
    magicSign: 'element',
    src: 'magog',
    text: '<p>На ваш выбор: Нанести 3 повреждения противнику слева или нанести 1 повреждение каждому противнику.</p>',
    initiative: 0,
  },
  {
    id: 'heat',
    title: 'жарёха',
    type: 'source',
    magicSign: 'element',
    src: 'heat',
    text: '<p>Нанесите 3 повреждения самому сильному противнику.</p>',
    initiative: 0,
  },
  {
    id: 'typhoon',
    title: 'тай фун',
    type: 'source',
    magicSign: 'element',
    src: 'typhoon',
    text: '<p>Нанесите 3 повреждения каждому противнику ходившему в этот раунд.</p>',
    initiative: 0,
  },
  {
    id: 'suppressing',
    title: 'подавлянский',
    type: 'quality',
    magicSign: 'nature',
    src: 'suppressing',
    text: '<p>Нанесите по 2 повреждения всем противникам слабее вас.</p>',
    initiative: 0,
  },
  {
    id: 'spiky',
    title: 'колючий',
    type: 'quality',
    magicSign: 'nature',
    src: 'spiky',
    text: '<p><b>Цель: </b>Противник справа</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>1 повреждение, и вы излечиваете 1 повреждение.</li><li><span>10+</span>3 повреждения, и вы излечиваете 3 повреждения.</li></ul>',
    initiative: 0,
  },
  {
    id: 'powerful',
    title: 'мощнятский',
    type: 'quality',
    magicSign: 'nature',
    src: 'powerful',
    text: '<p>Восстановите 2 ед. Жизни. Если вы все еще слабейший игрок, добавьте случайную карту из руки в ваше заклятие.</p>',
    initiative: 0,
  },
  {
    id: 'stunning',
    title: 'оглушающий',
    type: 'quality',
    magicSign: 'nature',
    src: 'stunning',
    text: '<p>Нанесите 2 повреждения случайному противнику. Повторите действие по 1 разу за каждый различный «ЗНАК» в вашем заклинании.</p>',
    initiative: 0,
  },
  {
    id: 'stone',
    title: 'камнетрясный',
    type: 'quality',
    magicSign: 'nature',
    src: 'stone',
    text: '<p>Первый противник слева получает 1 повреждение, второй - 2, третий - 3 и так далее, пока все противники не получат по повреждению.</p>',
    initiative: 0,
  },
  {
    id: 'rancid',
    title: 'протухший',
    type: 'quality',
    magicSign: 'dark',
    src: 'rancid',
    text: '<p>Сильнейший противник, из не игравших в этом раунде, должен сбросить карту «Качество» своего заклятия, если оно есть.</p>',
    initiative: 0,
  },
  {
    id: 'duel_hell',
    title: 'дуэльадский',
    type: 'quality',
    magicSign: 'dark',
    src: 'duel_hell',
    text: '<p><b>Цель: </b>Противник на ваш выбор</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>2 повреждения.</li><li><span>5-9</span>4 повреждения, вы получаете 1 повреждение.</li><li><span>10+</span>5 повреждений, вы получаете 2 повреждения.</li></ul>',
    initiative: 0,
  },
  {
    id: 'ritual',
    title: 'ритуалистичный',
    type: 'quality',
    magicSign: 'dark',
    src: 'ritual',
    text: '<p><b>Цель: </b>Противник на ваш выбор</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>Противнику ничего, вам 3 повреждения.</li><li><span>5-9</span>3 повреждения.</li><li><span>10+</span>5 повреждений.</li></ul>',
    initiative: 0,
  },
  {
    id: 'wormy',
    title: 'червивый',
    type: 'quality',
    magicSign: 'dark',
    src: 'wormy',
    text: '<p>Нанесите сильнейшему противнику по 2 повреждения за каждый знак «ТЬМЫ» в вашем заклятии.</p>',
    initiative: 0,
  },
  {
    id: 'brilliant',
    title: 'блестящий',
    type: 'quality',
    magicSign: 'mystery',
    src: 'brilliant',
    text: '<p><b>Цель: </b>Сильнейший противник</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>2 повреждения, вы получаете Сокровище.</li><li><span>10+</span>5 повреждений, вы получаете Сокровище.</li></ul>',
    initiative: 0,
  },
  {
    id: 'mystical',
    title: 'мистический',
    type: 'quality',
    magicSign: 'mystery',
    src: 'mystical',
    text: '<p>Нанесите противнику справа по 1 повреждению за каждый различный знак в заклятии, и за каждое ваше Сокровище.</p>',
    initiative: 0,
  },
  {
    id: 'two_faced',
    title: 'дву-личный',
    type: 'quality',
    magicSign: 'mystery',
    src: 'two_faced',
    text: '<p>Игрок по вашему выбору получает Сокровище. Затем он получает по 2 повреждения за каждое свое Сокровище.</p>',
    initiative: 0,
  },
  {
    id: 'faster',
    title: 'шустрый',
    type: 'quality',
    magicSign: 'mystery',
    src: 'faster',
    text: '<p>Во время определения ИНИЦИАТИВЫ у вас максимальное значение - вы ходите первым. Нанесите по 1 повреждению каждому противнику.</p>',
    initiative: 999,
  },
  {
    id: 'infernal',
    title: 'адско-стический',
    type: 'quality',
    magicSign: 'element',
    src: 'infernal',
    text: '<p>Нанесите по 1 повреждению каждому противнику за каждый знак «СТИХИЯ» в вашем заклятии.</p>',
    initiative: 0,
  },
  {
    id: 'explosive',
    title: 'взрывастый',
    type: 'quality',
    magicSign: 'element',
    src: 'explosive',
    text: '<p><b>Цель: </b>Противник на ваш выбор</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>3 повреждения, вы получаете 1 повреждение.</li><li><span>10+</span>4 повреждения, и вы выбираете и уничтожаете одно из сокровищ этого противника.</li></ul>',
    initiative: 0,
  },
  {
    id: 'tasty',
    title: 'вкусняцкий',
    type: 'quality',
    magicSign: 'element',
    src: 'tasty',
    text: '<p>Каждый противник с нечетным УРОВНЕМ ЖИЗНИ получает по 1 повреждению за каждый различный «ЗНАК» вашего заклятия.</p>',
    initiative: 0,
  },
  {
    id: 'cubic',
    title: 'кубикованый',
    type: 'quality',
    magicSign: 'element',
    src: 'cubic',
    text: '<p>Вы бросаете две кости. Все противники - по одной. Каждый, у кого то же, что и на одной из ваших костей, получает столько же повреждений.</p>',
    initiative: 0,
  },
  {
    id: 'cat_trouble',
    title: 'кот-а-строфный',
    type: 'quality',
    magicSign: 'illusion',
    src: 'cat_trouble',
    text: '<p>Все бросают кость. Вы +2 к своему броску. У кого наивысший результат, берут по сокровищу, остальные получают повреждения, у кого сколько выпало на костях.</p>',
    initiative: 0,
  },
  {
    id: 'disco',
    title: 'диско-шарный',
    type: 'quality',
    magicSign: 'illusion',
    src: 'disco',
    text: '<p>Эта карта копирует текст карты «Источник» или «Действие» вашего заклятия.</p>',
    initiative: 0,
  },
  {
    id: 'head_broken',
    title: 'ума-ломный',
    type: 'quality',
    magicSign: 'illusion',
    src: 'head_broken',
    text: '<p>Нанесите 3 повреждения случайному противнику. Затем оба возьмите по Сокровищу.</p>',
    initiative: 0,
  },
  {
    id: 'sharp',
    title: 'крутой',
    type: 'quality',
    magicSign: 'illusion',
    src: 'sharp',
    text: '<p>Противники слева и справа от вас должны выбрать и отдать вам одно из своих сокровищ или получить 3 повреждения.</p>',
    initiative: 0,
  },
  {
    id: 'divisor',
    title: 'ловушка-резка',
    type: 'action',
    magicSign: 'illusion',
    src: 'divisor',
    text: '<p><b>Цель: </b>Противник слева</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>2 повреждения.</li><li><span>5-9</span>3 повреждения.</li><li><span>10+</span>3 повреждения, цель должна уничтожить любое свое Сокровище или получить еще 3 повреждения.</li></ul>',
    initiative: 13,
  },
  {
    id: 'glare',
    title: 'блескослепье',
    type: 'action',
    magicSign: 'illusion',
    src: 'glare',
    text: '<p><b>Цель: </b>Противник на ваш выбор</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>1 повреждение, и добавляете случайную карту с руки в свое заклятие.</li><li><span>10+</span>Как выше, но карту выбираете сами.</li></ul>',
    initiative: 19,
  },
  {
    id: 'phantoms',
    title: 'фантомагады',
    type: 'action',
    magicSign: 'illusion',
    src: 'phantoms',
    text: '<p><b>Цель: </b>Противник справа</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>3 повреждения.</li><li><span>10+</span>4 повреждения.</li></ul>',
    initiative: 17,
  },
  {
    id: 'brain_pump',
    title: 'мозгосос',
    type: 'action',
    magicSign: 'illusion',
    src: 'brain_pump',
    text: '<p><b>Цель: </b>Противник на ваш выбор</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>3 повреждения.</li><li><span>10+</span>4 повреждения, и вы можете, на свой выбор, украсть одно из его сокровищ.</li></ul>',
    initiative: 15,
  },
  {
    id: 'fist_nature',
    title: 'кулак природы',
    type: 'action',
    magicSign: 'nature',
    src: 'fist_nature',
    text: '<p><b>Цель: </b>Противник слева</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>2 повреждения.</li><li><span>10+</span>4 повреждения.</li></ul>',
    initiative: 14,
  },
  {
    id: 'fountain_youth',
    title: 'фонтан молодости',
    type: 'action',
    magicSign: 'nature',
    src: 'fountain_youth',
    text: '<p><b>Цель: </b>Действует на себя</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>Без эффектов.</li><li><span>5-9</span>Восстановить 2 ед. Жизни.</li><li><span>10+</span>Восстановить 4 ед. Жизни.</li></ul>',
    initiative: 12,
  },
  {
    id: 'dismembered',
    title: 'расчленёнка',
    type: 'action',
    magicSign: 'nature',
    src: 'dismembered',
    text: '<p><b>Цель: </b>Сильнейший противник</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>2 повреждения.</li><li><span>5-9</span>3 повреждения.</li><li><span>10+</span>6 повреждений.</li></ul>',
    initiative: 2,
  },
  {
    id: 'dancing_snakes',
    title: 'змеетанцы',
    type: 'action',
    magicSign: 'nature',
    src: 'dancing_snakes',
    text: '<p><b>Цель: </b>Противники слева и справа</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>2 повреждения.</li><li><span>10+</span>по 2 повреждения за каждый знак «ПРИРОДА» в вашем заклятии.</li></ul>',
    initiative: 1,
  },
  {
    id: 'god_storm',
    title: 'божий шторм',
    type: 'action',
    magicSign: 'nature',
    src: 'god_storm',
    text: '<p><b>Цель: </b>Три противника справа</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение, вы восстанавливаете 1 ед. Жизни.</li><li><span>5-9</span>2 повреждения.</li><li><span>10+</span>2 повреждения, вы восстанавливаете 2 ед. Жизни.</li></ul>',
    initiative: 5,
  },
  {
    id: 'death_wish',
    title: 'жажда смерти',
    type: 'action',
    magicSign: 'dark',
    src: 'death_wish',
    text: '<p><b>Цель: </b>Противник справа от вас</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>2 повреждения, вы получаете 1 повреждение.</li><li><span>5-9</span>3 повреждения, вы получаете 1 повреждение.</li><li><span>10+</span>5 повреждений, вы получаете 1 повреждение.</li></ul>',
    initiative: 8,
  },
  {
    id: 'deal_devil',
    title: 'сделка с дьяволом',
    type: 'action',
    magicSign: 'dark',
    src: 'deal_devil',
    text: '<p><b>Цель: </b>Сильнейший противник</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>2 повреждения.</li><li><span>10+</span>2 повреждения, и если у него есть карта Действия в заклятии - украдите и используйте её в своем!</li></ul>',
    initiative: 18,
  },
  {
    id: 'exorcism',
    title: 'экзорсизм',
    type: 'action',
    magicSign: 'dark',
    src: 'exorcism',
    text: '<p><b>Цель: </b>Все противники</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>Вы получаете 1 повреждение.</li><li><span>5-9</span>2 повреждения, или 4 если у него есть жетон <span>ЖЕТОН ПОСЛЕДНИЙ БОЕВОЙ МАГ</span></li><li><span>10+</span>Как и выше, только в два раза больше!</li></ul>',
    initiative: 11,
  },
  {
    id: 'cute_death',
    title: 'мило-смертие',
    type: 'action',
    magicSign: 'dark',
    src: 'cute_death',
    text: '<p><b>Цель: </b>Слабейший противник</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>2 повреждения.</li><li><span>5-9</span>3 повреждения.</li><li><span>10+</span>4 повреждения.</li></ul>',
    initiative: 5,
  },
  {
    id: 'egg_blow',
    title: 'яйцобой',
    type: 'action',
    magicSign: 'mystery',
    src: 'egg_blow',
    text: '<p><b>Цель: </b>Слабейший противник</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>3 повреждения.</li><li><span>10+</span>5 повреждений, вы получаете Сокровище.</li></ul>',
    initiative: 7,
  },
  {
    id: 'dragon_stock',
    title: 'запас дракона',
    type: 'action',
    magicSign: 'mystery',
    src: 'dragon_stock',
    text: '<p><b>Цель: </b>Противники без сокровищ</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>2 повреждения.</li><li><span>10+</span>3 повреждения, вы получаете Сокровище.</li></ul>',
    initiative: 6,
  },
  {
    id: 'acid_shower',
    title: 'душ кислоты',
    type: 'action',
    magicSign: 'mystery',
    src: 'acid_shower',
    text: '<p><b>Цель: </b>Противники слева и справа</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>2 повреждения.</li><li><span>10+</span>4 повреждения, вы получаете Сокровище.</li></ul>',
    initiative: 4,
  },
  {
    id: 'vortex_force',
    title: 'вихрь силы',
    type: 'action',
    magicSign: 'mystery',
    src: 'vortex_force',
    text: '<p><b>Цель: </b>Все противники</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>Вы сбрасываете карту.</li><li><span>5-9</span>2 повреждения, вы сбрасываете 2 карты.</li><li><span>10+</span>Как и выше, + вы получаете Сокровище.</li></ul>',
    initiative: 16,
  },
  {
    id: 'thunderbolt',
    title: 'удар молнии',
    type: 'action',
    magicSign: 'element',
    src: 'thunderbolt',
    text: '<p><b>Цель: </b>Два противника слева</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>2 повреждения.</li><li><span>10+</span>4 повреждения.</li></ul>',
    initiative: 9,
  },
  {
    id: 'nuclear_bath',
    title: 'ядерная баня',
    type: 'action',
    magicSign: 'element',
    src: 'nuclear_bath',
    text: '<p><b>Цель: </b>Сильнейший противник</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>3 повреждения, и по 1 повреждению сидящим рядом с этим противником.</li><li><span>10+</span>5 повреждений, и как выше.</li></ul>',
    initiative: 10,
  },
  {
    id: 'chicken',
    title: 'курятина',
    type: 'action',
    magicSign: 'element',
    src: 'chicken',
    text: '<p><b>Цель: </b>Сильнейший противник</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>1 повреждение.</li><li><span>10+</span>7 повреждений.</li></ul>',
    initiative: 3,
  },
  {
    id: 'meatball',
    title: 'мясокуча',
    type: 'action',
    magicSign: 'element',
    src: 'meatball',
    text: '<p><b>Цель: </b>Все противники сильнее вас</p><p><b>Проверка силы</b></p><ul><li><span>1-4</span>1 повреждение.</li><li><span>5-9</span>3 повреждения.</li><li><span>10+</span>4 повреждения.</li></ul>',
    initiative: 20,
  },
];
