export enum CSSClasses {
  // base
  Component = 'component',
  Button = 'button',
  // start screen
  StartScreen = 'start-screen',
  StartScreenButton = 'start-screen__button',
  // player list
  PlayerList = 'player-list',
  PlayerListItem = 'player-list__item',
  PlayerAvatar = 'player__avatar',
  PlayerName = 'player__name',
  PlayerHero = 'player__hero',
  // cards spell
  Сard = 'card',
  СardСontainer = 'card__container',
  СardType = 'card-type',
  СardElement = 'card-element',
  СardContent = 'card__content',
  СardImage = 'card__image',
  СardTitle = 'card__title',
  СardText = 'card__text',
  // hero selection
  HeroSelection = 'hero-selection',
  Hero = 'hero',
  HeroImage = 'hero__image',
  HeroName = 'hero__name',
  HeroDisabled = 'hero__disabled',
  HeroSelected = 'hero__selected',
  // opponents cards
  OpponentsCards = 'opponents-cards',
  OpponentsCardsEmpty = 'opponents-cards--empty',
  OpponentCardItem = 'opponents-cards__item',
  // game screen
  GameScreen = 'game-screen',
  GameOpponentsCards = 'game-screen__opponent-cards',
  GamePlaySection = 'game-screen__play-section',
  GameCardsSection = 'game-screen__card-section',
  GameUILayer = 'game-screen__ui-layer',
  GameOpponentsInfo = 'game-screen__opponents-info-container',
  GameOpponentSection = 'game-screen__opponent-section',
  GamePlayerInfo = 'game-screen__player-info-container',
  GameControls = 'game-screen__game-buttons-container',
}
